name = "Calamity"
author = "dzenthai"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e562366bd6ffa4df77083b3e39056d74e3ce50006b0f89770b537dfa65d7a5b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
