#true = use the vanilla player model while this mod animates the player
#bosses_rise: roll and gauntlet animations of Bosses' Rise
#player_animator: Better Combat, Iron's Spellbooks, Spell Engine / Archers animations
#Thu Oct 01 17:10:08 QYZT 2026
bosses_rise=true
player_animator=true
