#=========[ Ancient Remnants Common Config ]=========
# Please prefer editing the config through the in-game 
# configuration screen (available via the mods list),
# as it includes many hints and quality-of-life improvements.
#====================================================
# Default: 100
# Range: > 0
hunter_monolith_placement_spacing = 100
# Default: 20
# Range: > 0
hunter_monolith_placement_separation = 20
hunter_monolith_biomes = ["minecraft:badlands"]
# Default: 100
# Range: > 0
warrior_monolith_placement_spacing = 100
# Default: 20
# Range: > 0
warrior_monolith_placement_separation = 20
warrior_monolith_biomes = ["minecraft:ice_spikes"]
# Default: 100
# Range: > 0
sentinel_monolith_placement_spacing = 100
# Default: 20
# Range: > 0
sentinel_monolith_placement_separation = 20
sentinel_monolith_biomes = ["minecraft:deep_frozen_ocean"]
# Default: 100
# Range: > 0
cherry_monument_placement_spacing = 100
# Default: 20
# Range: > 0
cherry_monument_placement_separation = 20
cherry_monument_biomes = ["minecraft:cherry_grove"]
# Default: 100
# Range: > 0
oakwood_monument_placement_spacing = 100
# Default: 20
# Range: > 0
oakwood_monument_placement_separation = 20
oakwood_monument_biomes = ["#minecraft:is_forest"]
# Default: 100
# Range: > 0
coniferous_monument_placement_spacing = 100
# Default: 20
# Range: > 0
coniferous_monument_placement_separation = 20
coniferous_monument_biomes = ["#minecraft:is_taiga"]
